### ISSUE TITLE
CLEANUP: No need to create RSTUDIO_PASSWORD in before.sh.erb for RStudio

### ISSUE THREAD

**Issue by HenrikBengtsson** [UCSF-CBI/c4-ondemand-interactive-apps#13]
I think we can drop

https://github.com/UCSF-CBI/c4-ondemand-interactive-apps/blob/0a19803a13d89fb0247261b33fb3df8b86724ced/RStudio/template/before.sh.erb#L4-L9

**Comment by hgputnam** [comment]
I tried removing all the lines and RStudio would not start. After some testing, we can remove the password lines but not the port line. We also need to tell rsc to use that specific port. I believe the reason is that code within the framework (not meant to be modified) is looking for an rserver on the port that was generated in the before block when it launches the session and opens a new browser tab. Probably something a real coder could change but might make things difficult when we upgrade OnDemand.

**Comment by HenrikBengtsson** [comment]
Oh, yes of course, the port is needed for OnDemand to know what to proxy.

**Comment by HenrikBengtsson** [comment]
Was done in https://github.com/UCSF-CBI/c4-ondemand-interactive-apps/commit/bc43b9ee5b833dd0466dad02bd10415e7c8e5b17
